### ISSUE TITLE
Magnus Launcher Prototyping and Research

### ISSUE THREAD

**Issue by Alexbay218** [Chantilly612Code/612-2016#51] opened 2016-02-02 20:36 UTC
![flywheellauncher](https://cloud.githubusercontent.com/assets/9091117/12763427/64af38c2-c9c2-11e5-9684-db8dd1b51b23.png)
Research and prototype whether it is feasible to implement magnus shooter. dev-magnus will house algorithms.

**Comment by Mister-GoodwinLu** [comment] 2016-02-02 20:50
it seems that magnus force would make it easier for us, since less force is necessary to overcome the gravity due to the backspin nature of the magnus spin. As Wikipedia states:
"The curved path of a golf ball known as slice or hook is due largely to the ball's spinning motion (about its vertical axis) and the Magnus effect, causing a horizontal force that moves the ball from a straight line in its trajectory.[18] Backspin (upper surface rotating backwards from the direction of movement) on a golf ball causes a vertical force that counteracts the force of gravity slightly, and enables the ball to remain airborne a little longer than it would were the ball not spinning: this allows the ball to travel farther than a non-spinning (about its horizontal axis) ball.

In table tennis, the Magnus effect is easily observed, because of the small mass and low density of the ball. An experienced player can place a wide variety of spins on the ball. Table tennis rackets usually have a surface made of rubber to give the racket maximum grip on the ball to impart a spin.

The Magnus effect is not responsible for the movement of the cricket ball seen in swing bowling,[19] although it does contribute to the motion known as drift in spin bowling.

In airsoft, a system known as hop-up is used to create a backspin on a fired BB, which will greatly increase its range, using the Magnus effect in a similar manner as in golf.

In paintball, Tippmann's Flatline Barrel System also takes advantage of the Magnus effect by imparting a backspin on the paintballs, which increases their effective range by counteracting gravity.

In baseball, pitchers often impart different spins on the ball, causing it to curve in the desired direction due to the Magnus effect. The PITCHf/x system measures the change in trajectory caused by Magnus in all pitches thrown in Major League Baseball.[20]"

**Comment by Alexbay218** [comment] 2016-02-02 22:33
I have looked into it, and we will not be able to create forward or back spin on the ball. The point is to apply left or right spin to curve ball trajectory. This means, instead of turn the whole robot, the magnus shooter can aim instead.

**Comment by Mister-GoodwinLu** [comment] 2016-02-03 21:34
hmmm, I suppose that makes sense. :/

**Comment by ChampD** [comment] 2016-02-06 15:10
At this point, this goal is both going to take a long time that we do not have, as well as being really unnecessary. I think we should close this issue for now, and revisit it when basic bot functionality is finalized.

**Closed by ChampD** 2016-02-06 15:10 UTC
Labels: boulder mechanisms, enhancement, robot code
